version: '3.8'

services:
  app:
    build:
      context: ./LerningApp/docker/php
    container_name: LerningApp
    working_dir: /var/www/html
    volumes:
      - ./LerningApp/src:/var/www/html
    networks:
      - LerningApp

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./LerningApp/src:/var/www/html
      - ./LerningApp/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - LerningApp

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3333:3333"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    command: --port=3333
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - LerningApp

volumes:
  db-data:

networks:
  LerningApp:
    driver: bridge
